# Generated by Django 5.2.17 on 2026-10-01 08:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import marketplace.models
import marketplace.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use international format, e.g. +77001234567.')])),
                ('role', models.CharField(choices=[('carrier', 'Перевозчик'), ('shipper', 'Грузовладелец')], max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', validators=[marketplace.validators.validate_attachment])),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_city', models.CharField(max_length=120)),
                ('from_address', models.CharField(max_length=255)),
                ('to_city', models.CharField(max_length=120)),
                ('to_address', models.CharField(max_length=255)),
                ('loading_date', models.DateField()),
                ('unloading_date', models.DateField(blank=True, null=True)),
                ('cargo_name', models.CharField(max_length=200)),
                ('cargo_type', models.CharField(max_length=80)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('body_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_type', models.CharField(default='bank_transfer', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Опубликован'), ('assigned', 'Исполнитель выбран'), ('in_transit', 'В пути'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('bin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')])),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Не проверена'), ('pending', 'На проверке'), ('verified', 'Проверена'), ('rejected', 'Отклонена')], default='unverified', max_length=12)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('document', 'Документ'), ('location', 'Местоположение')], default='text', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to=marketplace.models.attachment_path, validators=[marketplace.validators.validate_attachment])),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('entity_id', models.PositiveBigIntegerField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=12)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.cargo')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('carrier_selected', 'Перевозчик выбран'), ('heading_to_pickup', 'Машина направляется'), ('loading', 'На загрузке'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='carrier_selected', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='marketplace.cargo')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_orders', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='marketplace.offer')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipped_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='marketplace.order'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.order')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('body_type', models.CharField(max_length=30)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_city', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('busy', 'Занят'), ('inactive', 'Неактивен')], default='available', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.vehicle'),
        ),
        migrations.AddField(
            model_name='offer',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='marketplace.vehicle'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['from_city', 'to_city', 'loading_date'], name='marketplace_from_ci_f2ba78_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0), ('volume_m3__gte', 0), ('weight_kg__gt', 0)), name='cargo_positive_values'),
        ),
        migrations.AddConstraint(
            model_name='favoritecargo',
            constraint=models.UniqueConstraint(fields=('user', 'cargo'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('order', 'author'), name='one_review_per_author_and_order'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['completed', 'cancelled']), _negated=True), fields=('vehicle',), name='one_active_order_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('cargo', 'carrier'), name='one_pending_offer_per_carrier'),
        ),
    ]
